# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interface', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='heartbeat_interval',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
