# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interface', '0003_sensor_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='state',
            field=models.CharField(choices=[('ok', 'ok'), ('broken', 'broken')], default='ok', max_length=10),
        ),
    ]
