# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 09:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0006_soundsource'),
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('speed_of_sound', models.FloatField(default=340.29)),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.World'),
        ),
        migrations.AddField(
            model_name='soundsource',
            name='world',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.World'),
        ),
    ]
