# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_auto_20170121_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interface.World'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='soundsource',
            name='world',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interface.World'),
            preserve_default=False,
        ),
    ]
