# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0008_auto_20170121_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='failure_probability',
            field=models.FloatField(default=0.01),
        ),
    ]
