# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0009_sensor_failure_probability'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntBound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('bound_type', models.CharField(choices=[('inclusive', 'inclusive'), ('exclusive', 'exclusive')], default='inclusive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IntInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lower_bound', to='interface.IntBound')),
                ('upper_bound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upper_bound', to='interface.IntBound')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkAdapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Position')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.World')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter_from', to='interface.NetworkAdapter')),
                ('adapter_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adapter_to', to='interface.NetworkAdapter')),
                ('possible_latency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.IntInterval')),
            ],
        ),
        migrations.AddField(
            model_name='sensor',
            name='adapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.NetworkAdapter'),
        ),
    ]
