# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_auto_20170217_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_adapters', models.ManyToManyField(to='interface.NetworkAdapter')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Position')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SoftwareState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(choices=[('sensor_controller', 'sensor_controller'), ('tdoa_controller', 'tdoa_controller'), ('tdoa_locator', 'tdoa_locator')], default='sensor_controller', max_length=50)),
                ('is_active', models.BooleanField()),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.Computer')),
            ],
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='adapter',
        ),
        migrations.AddField(
            model_name='computer',
            name='sensors',
            field=models.ManyToManyField(to='interface.Sensor'),
        ),
        migrations.AddField(
            model_name='computer',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interface.World'),
        ),
        migrations.AlterUniqueTogether(
            name='softwarestate',
            unique_together=set([('computer', 'software')]),
        ),
    ]
