# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('interface', '0013_auto_20170219_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='is_active_position_determinator',
            field=models.BooleanField(default=False),
        ),
    ]
